// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOpt
/// ions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXxSH6mFiX6EuMl-Zaveo4yUUymBHKHI',
    appId: '1:323354310069:web:418cd44d9b578d300715fc',
    messagingSenderId: '323354310069',
    projectId: 'project-01-auth',
    authDomain: 'project-01-auth.firebaseapp.com',
    databaseURL: 'https://project-01-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-01-auth.appspot.com',
    measurementId: 'G-3QGB266H89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYcdfbfuuJykq_OvVGtUiHrcd3R07bk8',
    appId: '1:323354310069:android:7fd1add635b3ca280715fc',
    messagingSenderId: '323354310069',
    projectId: 'project-01-auth',
    databaseURL: 'https://project-01-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-01-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA845dGGtGOgFQhUON8CCn5d6HhMAXzwZA',
    appId: '1:323354310069:ios:68cab6c6272aa36d0715fc',
    messagingSenderId: '323354310069',
    projectId: 'project-01-auth',
    databaseURL: 'https://project-01-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-01-auth.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA845dGGtGOgFQhUON8CCn5d6HhMAXzwZA',
    appId: '1:323354310069:ios:68cab6c6272aa36d0715fc',
    messagingSenderId: '323354310069',
    projectId: 'project-01-auth',
    databaseURL: 'https://project-01-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-01-auth.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBXxSH6mFiX6EuMl-Zaveo4yUUymBHKHI',
    appId: '1:323354310069:web:3fdb8ea1816bfc870715fc',
    messagingSenderId: '323354310069',
    projectId: 'project-01-auth',
    authDomain: 'project-01-auth.firebaseapp.com',
    databaseURL: 'https://project-01-auth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-01-auth.appspot.com',
    measurementId: 'G-6LMQCDVP29',
  );
}
